vich_uploader:
    db_driver: orm

    mappings:
        produit_photo:
            uri_prefix: '%produit_photo'
            upload_destination: '%kernel.project_dir%/public%produit_photo%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: false